### PR TITLE
Svg images created #21

### LINKED ISSUE #21: Missing source files of png images
PNG images should ideally be replaced by SVG images. That way we don't have to maintain 2 versions of the same image. 
- [ ] besad.png
- [x] darcyf.png
- [x] darcyf_zoomed.png
- [x] ghosts.png
- [x] kp.png
- [x] penstock.png
- [x] pipe.png
- [x] SharpOrificeSurgeTank.png
- [x] simplegen.png
- [x] surgepic.png
- [x] ThrottleValveSurgeTank.png
- [x] turbinepic.png

@pandeysudan27 could you see if you can get hold of pdfs that can be converted to SVGs or recreate them if not possible?

### PR DESCRIPTION
**Pull request by pandeysudan27**
Some svg images were created. The color code of water and air is taken lighter so that latex text can be seen easily. Otherwise its an extra job to create a background image for the latex text, probably white; I am afraid, the whole figure looks ugly. (It looks like ghosts.png was never used) . May be we need to check unused images. (@dietmarw Do you have any short method to check if all the images where used in the OpenHPL).

### CODE REVIEW

**Review by dietmarw — CHANGES_REQUESTED** [review]
A couple of things. 

* The `penstock.png` still needs to be converted
* I understand the issue with the colour but then we should agree on some standard colour code: My proposal is RGB={20,220,220} and then also the connector colours should be adapted.
 * keep air colour  green
 * Some of the images have offset of fill colour and boundary e.g., `STSimple.svg` but check others too.
 * When changing from png to svg also the references in the modelica code need to be updated and proper width needs to be set in addition. E.g., ` width="800"`
Currently these png are still linked:
```
~/.workspace/OpenHPL/OpenHPL[Svgimages]$ grep -r "\\.png"
Binary file Resources/Documents/Report.docx matches
Waterway/PenstockKP.mo:<p><img src=\"modelica://OpenHPL/Resources/Images/penstock.png\" style=\"width:50%\"></p>
Waterway/BendPipe.mo:<p><img src=\"modelica://OpenHPL/Resources/Images/MinorLoss.png\"/></p>
Waterway/Pipe.mo:    <p align=\"center\"><img src=\"modelica://OpenHPL/Resources/Images/pipe.png\"> </p>
Waterway/Penstock.mo:<p><img src=\"modelica://OpenHPL/Resources/Images/penstock.png\"></p>
Waterway/Penstock.mo:<p><img src=\"modelica://OpenHPL/Resources/Images/besad.png\"></p>
Functions/KP07/KPfunctions/GhostCells.mo:<p><img src=\"modelica://OpenHPL/Resources/Images/ghosts.png\"/></p>
Functions/DarcyFriction/fDarcy.mo:<p><img src=\"modelica://OpenHPL/Resources/Images/darcyf.png\"/></p>
Functions/DarcyFriction/fDarcy.mo:<p><img src=\"modelica://OpenHPL/Resources/Images/darcyf_zoomed.png\"/></p>
ElectroMech/Turbines/Turbine.mo:<img src=\"modelica://OpenHPL/Resources/Images/turbinepic.png\">
ElectroMech/Generators/SimpleGen.mo:<img src=\"modelica://OpenHPL/Resources/Images/simplegen.png\">
ElectroMech/Generators/SimpleGen2.mo:<img src=\"modelica://OpenHPL/Resources/Images/simplegen.png\">
```

**Comment by dietmarw** [comment]
One more:
 * `kp.svg` contains some additional arrows outside the view box. That needs to be removed.

**Comment by pandeysudan27** [comment]
I got the way to fix the arrow for denoting flow like Vdot, velocity-v, etc. in STSimple and others. I made changes in gitkraken, thanks for the video. Is it possible to work with Lyx rather than Latex for Userguide; I have a very slow workflow with Latex?

**Comment by dietmarw** [comment]
No please no Lyx.

**Comment by pandeysudan27** [comment]
OK.

**Comment by dietmarw** [comment]
@pandeysudan27 Did you have any chance on working further on this PR fixing the issues I mentioned above?

**Comment by dietmarw** [comment]
I've now replaced all png files except `besad.png`. Other things left:
- common colour for water: It should be the same as in the connectors: `{0,128,255}`
- air colour should  be green: `{0,255,128}´
- fix the gaps between boundaries and fill patterns

**Review by dietmarw — APPROVED** [review]

**Pull request merged**
